import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * WSO2 Integrator Documentation — Sidebar Configuration
 *
 * Autogenerated from the docs/ folder structure (see Docs Repo & Branch
 * Strategy §4 for the section order). Each top-level folder carries a
 * `_category_.json` fixing its label and position; ordering within a
 * folder falls back to alphabetical unless a doc sets `sidebar_position`.
 *
 * Switched from a hand-maintained doc-id list to autogenerated during the
 * Phase 3 IA migration — with ~400 files moving across 12 sections, a
 * manually curated list is exactly what produced stale-reference bugs
 * earlier in this migration (see git history on this branch). This
 * removes that whole class of bug for the restructured content.
 *
 * `manage/` is not part of the target IA — it's a temporary holding pen
 * for cloud-only content that belongs on `main`, not deleted here to
 * avoid data loss. See its `_category_.json` and the migration commit
 * message for details.
 */
const sidebars: SidebarsConfig = {
  mainSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
