import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * WSO2 Integration Platform Documentation (SaaS) — Sidebar Configuration
 *
 * Autogenerated from the docs/ folder structure (see Docs Repo & Branch
 * Strategy §4 for the section order). Each top-level folder carries a
 * `_category_.json` fixing its label and position; ordering within a
 * folder falls back to alphabetical unless a doc sets `sidebar_position`.
 *
 * Mirrors the same switch made on wso2-integrator: a hand-maintained
 * doc-id list (this file previously ran ~2500 lines, mostly the embedded
 * connector catalog) is exactly what produces stale-reference bugs during
 * a restructure this size. Autogenerated removes that whole class of bug.
 *
 * platform-overview, editor, develop, test, customize, migrate, and
 * guides are synced from wso2-integrator (the shared-content source of
 * truth) — do not hand-edit those here; send changes to wso2-integrator
 * instead. get-started, deploy, operate, manage, and reference are
 * authored independently on this branch (cloud-specific).
 */
const sidebars: SidebarsConfig = {
  mainSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
