import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * WSO2 Integration Platform Documentation (SaaS) — Sidebar Configuration
 *
 * Autogenerated from the docs/ folder structure (see Docs Repo & Branch
 * Strategy §4 for the section order). Each top-level folder carries a
 * `_category_.json` fixing its label and position; ordering within a
 * folder falls back to alphabetical unless a doc sets `sidebar_position`.
 *
 * Mirrors the same switch made on wso2-integrator: a hand-maintained
 * doc-id list (this file previously ran ~2500 lines, mostly the embedded
 * connector catalog) is exactly what produces stale-reference bugs during
 * a restructure this size. Autogenerated removes that whole class of bug.
 *
 * platform-overview, editor, develop-and-test, migrate, and guides are
 * synced from wso2-integrator (the shared-content source of truth) — do
 * not hand-edit those here; send changes to wso2-integrator instead.
 * get-started, deploy, manage, observe, and reference are authored
 * independently on this branch (cloud-specific).
 *
 * There is deliberately no `customize/` section (removed -- its planned
 * scope was custom connectors, custom AI tools, and reusable libraries,
 * all of which already live elsewhere: connector authoring/catalog is
 * wso2-connectors-only by policy, custom connector generation is covered
 * under editor/copilot/, and reusable libraries are fully covered under
 * develop-and-test/organize-workbench/library/ and editor/views/library-view.md.
 * A standalone section would have been either duplicate content or a
 * near-empty page of cross-links). If wso2-integrator's own customize/
 * still exists, this same removal needs to happen there too, or the next
 * sync recreates it here.
 *
 * There used to be a hand-authored "Learn Ballerina" external link
 * appended here too. Removed -- the same link now lives in
 * ProductDocsLinks (src/components/ProductDocsLinks), right after
 * "WSO2 Integrator: SI", so it doesn't need a second appearance as its
 * own top-level sidebar entry.
 */
const sidebars: SidebarsConfig = {
  mainSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
